stages:
  - build
xx-wiki:
  stage: build
  script:
    - p=`pwd`
    - echo $p
    - gitbook install
    - gitbook build
    - nohup gitbook serve --port 4000 >> /opt/logs/gitbook/wiki.mym.log 2>&1 &
