stages:
  - build
test-wiki:
    #下面这里是项目的tag   根据上面注册GitLab Runner第4步设置的tags填写
  tags:   
    - dev
  stage: build
  script:
    - p=`pwd`
    - whoami
    - echo $p
    - sudo  /root/.nvm/versions/node/v12.16.3/bin/gitbook install
    - sudo  /root/.nvm/versions/node/v12.16.3/bin/gitbook build
    - setsid nohup sh startup.sh > nohup.out 2>&1 &
